apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Chart.Name }}-service
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
  type: {{ .Values.type }}