apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-transaction-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Chart.Name }}-transaction
  ports:
    - port: {{ .Values.transaction.port }}
      targetPort: {{ .Values.transaction.port }}
  type: {{ .Values.transaction.service.type }}