apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-account-secret
  namespace: {{ .Values.namespace }}
stringData:
  DB_HOST: {{ .Chart.Name }}-mysql-service
  DB_USER: {{ .Values.env.dbUser }}
  DB_PASS: {{ .Values.env.dbPass }}
  DB_NAME: {{ .Values.env.dbName }}
  REDIS_HOST: {{ .Values.env.redisHost }}