apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-user-service
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Chart.Name }}-user
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}