apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-reporting-config
  namespace: {{ .Values.namespace }}
data:
  DB_HOST: "{{ .Values.env.dbHost }}"
  DB_USER: "{{ .Values.env.dbUser }}"
  DB_NAME: "{{ .Values.env.dbName }}"
  PORT: "{{ .Values.port }}"